FROM scratch
MAINTAINER lhchavez "lhchavez@omegaup.com"
EXPOSE 11302

ADD root/grader /
ADD cmd/grader/data /data
ADD bin/x86_64/grader /usr/bin

VOLUME ["/var/lib/omegaup", "/etc/omegaup/grader", "/var/log/omegaup", "/data"]

ENTRYPOINT ["/usr/bin/grader"]
