FROM ubuntu:22.04 AS backend

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
        ca-certificates \
        curl \
        openjdk-17-jre-headless \
        wait-for-it \
        xz-utils && \
    /usr/sbin/update-ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean

RUN curl -sL https://github.com/omegaup/libinteractive/releases/download/v2.0.29/libinteractive.jar \
        -o /usr/share/java/libinteractive.jar && \
    useradd --create-home --shell=/bin/bash ubuntu && \
    mkdir -p /etc/omegaup/gitserver /var/log/omegaup /var/lib/omegaup/problems.git && \
    chown -R ubuntu /var/log/omegaup /var/lib/omegaup

ARG RELEASE
ENV RELEASE=$RELEASE
RUN curl --fail --location --retry 5 --retry-delay 2 --retry-all-errors \
        https://github.com/omegaup/quark/releases/download/${RELEASE}/omegaup-backend.tar.xz \
        -o /tmp/omegaup-backend.tar.xz && \
    tar xJf /tmp/omegaup-backend.tar.xz -C / && \
    rm /tmp/omegaup-backend.tar.xz

USER ubuntu
WORKDIR /var/lib/omegaup
